#!/bin/sh
#
# @name 6DoF hexacopter SITL
#
# @type Hexarotor x
#
# @maintainer Kousheek Chakraborty <k.chakraborty@saxion.nl>
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=peach}

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

param set-default MAV_TYPE 13

param set-default CA_ROTOR0_PX 0.0
param set-default CA_ROTOR0_PY 0.338
param set-default CA_ROTOR0_PZ 0.0
param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR0_AX 0.5
param set-default CA_ROTOR0_AY 0.0
param set-default CA_ROTOR0_AZ -0.8660254

param set-default CA_ROTOR1_PX 0.0
param set-default CA_ROTOR1_PY -0.338
param set-default CA_ROTOR1_PZ 0.0
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR1_AX 0.5
param set-default CA_ROTOR1_AY 0
param set-default CA_ROTOR1_AZ -0.8660254

param set-default CA_ROTOR2_PX 0.3
param set-default CA_ROTOR2_PY -0.18
param set-default CA_ROTOR2_PZ 0.0
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR2_AX -0.25
param set-default CA_ROTOR2_AY -0.4330127
param set-default CA_ROTOR2_AZ -0.8660254

param set-default CA_ROTOR3_PX -0.3
param set-default CA_ROTOR3_PY 0.18
param set-default CA_ROTOR3_PZ 0.0
param set-default CA_ROTOR3_KM 0.05
param set-default CA_ROTOR3_AX -0.25
param set-default CA_ROTOR3_AY -0.4330127
param set-default CA_ROTOR3_AZ -0.8660254

param set-default CA_ROTOR4_PX 0.3
param set-default CA_ROTOR4_PY 0.18
param set-default CA_ROTOR4_PZ 0.0
param set-default CA_ROTOR4_KM 0.05
param set-default CA_ROTOR4_AX -0.25
param set-default CA_ROTOR4_AY 0.4330127
param set-default CA_ROTOR4_AZ -0.8660254

param set-default CA_ROTOR5_PX -0.3
param set-default CA_ROTOR5_PY -0.18
param set-default CA_ROTOR5_PZ 0.0
param set-default CA_ROTOR5_KM -0.05
param set-default CA_ROTOR5_AX -0.25
param set-default CA_ROTOR5_AY 0.4330127
param set-default CA_ROTOR5_AZ -0.8660254

param set-default SIM_GZ_EN 1

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150
param set-default SIM_GZ_EC_MIN5 150
param set-default SIM_GZ_EC_MIN6 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_MAX6 1000

param set-default MPC_XY_VEL_ALL 5.0
